export const RISK_WEIGHTS: Record<string, number> = {
  destructive_delete: 40,
  file_delete: 25,
  destructive_git_operation: 35,
  removes_untracked_files: 35,
  network_pipe_exec: 50,
  privilege_escalation: 25,
  sensitive_path_write: 30,
  package_manager_mutation: 25,
  package_global_mutation: 25,
  wildcard_mass_operation: 20,
  background_process: 15,
  docker_destructive: 35,
  scope_escape: 45,
  agent_config_write: 30
};

export const IMPORTANT_FILES = [
  ".env",
  ".env.local",
  ".npmrc",
  ".pypirc",
  "package.json",
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "requirements.txt",
  "pyproject.toml",
  "Cargo.toml",
  "Cargo.lock",
  "go.mod",
  "go.sum",
  "Dockerfile",
  "docker-compose.yml",
  "CLAUDE.md",
  ".codex/config.toml",
  ".claude/settings.json"
];

export const SENSITIVE_FILES = [
  ".env",
  ".env.local",
  ".npmrc",
  ".pypirc",
  ".git/config",
  ".ssh",
  ".aws",
  ".gitconfig",
  "package.json",
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "requirements.txt",
  "pyproject.toml",
  "Cargo.toml",
  "Cargo.lock",
  "go.mod",
  "go.sum",
  "CLAUDE.md",
  ".codex/config.toml",
  ".claude/settings.json"
];
